### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by oren** [joshymcd/mycroft-electro#1]
> edit config.json in mycroft-magic-mirror folder with two paths to mycroft-core and this mycroft-magic-mirror"

what is mycroft-magic-mirror?

I see config.json in the source folder:
```
    "mycroftCoreDir":"/home/oren/mycroft-core",
    "installDir":"/home/pi/mycroft-electro"
```

A few questions:
1. what is installDir?  maybe it's where i located this repo
1. I run it with npm start but it's not responding to my voice and I don't hear any feedback. I also tried to write something in the textbox but nothing happend.

## System info

lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

uname -a
```
Linux oren 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks!

**Comment by oren** [comment]
Some useful output for troubleshooting the issue:

```
 npm start 

> Magic-Mycroft-Mirror@1.0.0 start /home/oren/p/mycroft/mycroft-electro
> webpack && electron .

Hash: 1c337ddf91da7ed915f7
Version: webpack 1.15.0
Time: 2636ms
                       Asset       Size  Chunks             Chunk Names
                  index.html  685 bytes          [emitted]  
                   bundle.js    1.21 MB       0  [emitted]  main
                 electron.js  848 bytes          [emitted]  
kill_descendant_processes.sh  327 bytes          [emitted]  
 [208] ./source/plugins ^\.\/.*\.js$ 294 bytes {0} [built]
    + 225 hidden modules
```

Also `ps aux|grep python` shows nothing.

**Comment by joshymcd** [comment]
I haven't had time to update this to be compatible with the latest versions of mycroft 
I'm planning to do a rewrite when I have some more time but I'm not going to do any more work on this codebase in the meantime I'm afraid :(
